name: Deploy via SSH

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH with Password
      run: |
        set -e
        mkdir -p ~/.ssh
        echo "${{ secrets.CPANEL_SSH_PRIVATE_KEY }}" > ~/.ssh/consoft_ssh
        chmod 600 ~/.ssh/consoft_ssh
        ssh-keyscan -H s1350.use1.mysecurecloudhost.com >> ~/.ssh/known_hosts
        eval "$(ssh-agent -s)"
        echo "${{ secrets.SSH_KEY_PASSWORD }}" | ssh-add ~/.ssh/consoft_ssh

    - name: Deploy Files via SSH
      run: |
        scp -r ./create-testfile.txt allevent@s1350.use1.mysecurecloudhost.com:/home/allevent/reacttest.gephelssystems.com/frontend

    - name: Verify Deployment
      run: |
        ssh allevent@s1350.use1.mysecurecloudhost.com "ls -l /home/allevent/reacttest.gephelssystems.com/frontend/create-testfile.txt"
