name: Deploy via SSH

on:
  push:
    branches:
      - main

jobs:
  cache:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      # Install dependencies before caching
      - name: Install Frontend Dependencies
        run: |
          cd frontend
          npm install

      - name: Install Backend Dependencies
        run: |
          cd backend
          npm install

      # Cache the node_modules directories for both frontend and backend
      - name: Cache Frontend Dependencies
        uses: actions/cache@v3
        with:
          path: frontend/node_modules
          key: frontend-node-modules-${{ hashFiles('frontend/package-lock.json') }}
          restore-keys: |
            frontend-node-modules-

      - name: Cache Backend Dependencies
        uses: actions/cache@v3
        with:
          path: backend/node_modules
          key: backend-node-modules-${{ hashFiles('backend/package-lock.json') }}
          restore-keys: |
            backend-node-modules-

  deploy_frontend:
    runs-on: ubuntu-latest
    needs: cache
    if: github.event_name == 'push' && contains(github.event.head_commit.message, 'frontend')
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH with New Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.CPANEL_SSH_PRIVATE_KEY }}" > ~/.ssh/consoft_ssh_new
          chmod 600 ~/.ssh/consoft_ssh_new
          ssh-keyscan -H s1346.use1.mysecurecloudhost.com >> ~/.ssh/known_hosts
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/consoft_ssh_new

      - name: Test SSH Connection
        run: |
          ssh -v -i ~/.ssh/consoft_ssh_new allevent@s1346.use1.mysecurecloudhost.com "echo 'Connection successful'"

      - name: Build Frontend
        run: |
          cd frontend
          CI=false npm install
          CI=false npm run build

      - name: Deploy Frontend via SSH
        run: |
          scp -v -i ~/.ssh/consoft_ssh_new -r ./frontend/build/* allevent@s1346.use1.mysecurecloudhost.com:/home/allevent/reacttest.gephelssystems.com/admin/

  deploy_user:
    runs-on: ubuntu-latest
    needs: cache
    if: github.event_name == 'push' && contains(github.event.head_commit.message, 'user')
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH with New Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.CPANEL_SSH_PRIVATE_KEY }}" > ~/.ssh/consoft_ssh_new
          chmod 600 ~/.ssh/consoft_ssh_new
          ssh-keyscan -H s1346.use1.mysecurecloudhost.com >> ~/.ssh/known_hosts
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/consoft_ssh_new

      - name: Test SSH Connection
        run: |
          ssh -v -i ~/.ssh/consoft_ssh_new allevent@s1346.use1.mysecurecloudhost.com "echo 'Connection successful'"

      - name: Build User Module
        run: |
          cd user
          CI=false npm install
          CI=false npm run build

      - name: Deploy User via SSH
        run: |
          scp -v -i ~/.ssh/consoft_ssh_new -r ./user/build/* allevent@s1346.use1.mysecurecloudhost.com:/home/allevent/reacttest.gephelssystems.com/user/

  deploy_backend:
    runs-on: ubuntu-latest
    needs: cache
    if: github.event_name == 'push' && contains(github.event.head_commit.message, 'backend')
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH with New Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.CPANEL_SSH_PRIVATE_KEY }}" > ~/.ssh/consoft_ssh_new
          chmod 600 ~/.ssh/consoft_ssh_new
          ssh-keyscan -H s1346.use1.mysecurecloudhost.com >> ~/.ssh/known_hosts
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/consoft_ssh_new

      - name: Test SSH Connection
        run: |
          ssh -v -i ~/.ssh/consoft_ssh_new allevent@s1346.use1.mysecurecloudhost.com "echo 'Connection successful'"

      - name: Deploy Backend via SSH
        run: |
          scp -v -i ~/.ssh/consoft_ssh_new -r ./backend/* allevent@s1346.use1.mysecurecloudhost.com:/home/allevent/reacttest.gephelssystems.com/

      - name: Restart Node.js Application if changes detected
        run: |
          ssh -i ~/.ssh/consoft_ssh_new allevent@s1346.use1.mysecurecloudhost.com "
            source /home/allevent/nodevenv/reacttest.gephelssystems.com/20/bin/activate && 
            cd /home/allevent/reacttest.gephelssystems.com &&
            npm install &&
            npm start
          "
