name: Build and Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install lftp
        run: sudo apt-get update && sudo apt-get install -y lftp

      - name: Create a test file
        run: |
          mkdir -p frontend/build
          echo "This is a test file to check FTP connection" > frontend/build/testfile.txt

      - name: Upload file to CPanel
        run: |
          lftp -d -e "
              open ftp://ftp.gephelssystems.com:21;
              set ftp:ssl-allow yes;
              set ftp:ssl-force yes;
              set ssl:verify-certificate no;
              set ftp:passive-mode yes;
              set ftp:ssl-protect-data yes;
              set net:timeout 10;
              set net:max-retries 3;
              user *** ***;
              cd /home/gephelss/public_html/app;
              put frontend/build/testfile.txt;
              bye
          " | tee lftp-log.txt




      - name: Debug Workspace Structure (Optional)
        run: |
          echo "Listing all files in the workspace"
          ls -R
