name: Deploy via SSH

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH with Password
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.CPANEL_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H your.server.com >> ~/.ssh/known_hosts

        # Use ssh-agent to handle the password-protected key
        eval "$(ssh-agent -s)"
        echo "${{ secrets.SSH_KEY_PASSWORD }}" | ssh-add ~/.ssh/id_rsa
    - name: Deploy Files via SSH
      run: |
        scp -r ./your-files user@your.server.com:/path/to/deploy
