name: Build and Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Get the public IP address of GitHub Actions runner
      - name: Get public IP
        run: curl -s https://ifconfig.me

      # Checkout code from GitHub
      - name: Checkout code
        uses: actions/checkout@v3

      # Install lftp
      - name: Install lftp
        run: sudo apt-get install -y lftp

      # Create a test file to upload
      - name: Create a test file
        run: |
          mkdir -p frontend/build
          echo "This is a test file to check FTP connection" > frontend/build/testfile.txt

      # Test FTP connection and upload file
      - name: Upload file to CPanel
        run: |
          echo "Testing FTP connection and uploading file"
          lftp -d -e "
          open ${{ secrets.FTP_SERVER }};
          set ftp:ssl-allow yes;
          set ftp:ssl-force yes;
          set ftp:passive-mode yes;
          set ftp:transfer-type binary;  # Correct option for binary transfer mode
          cd /home/gephelss/public_html/app;  # Navigate to the target directory
          put frontend/build/testfile.txt;  # Upload the file
          quit
          " -u ${{ secrets.FTP_USERNAME }},${{ secrets.FTP_PASSWORD }}

      - name: Debug workspace
        run: ls -R
        
