name: Deploy via SSH

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up SSH with New Key
    - name: Set up SSH with New Key
      run: |
        set -e
        mkdir -p ~/.ssh
        echo "${{ secrets.CPANEL_SSH_PRIVATE_KEY }}" > ~/.ssh/consoft_ssh_new
        chmod 600 ~/.ssh/consoft_ssh_new
        ssh-keyscan -H s1346.use1.mysecurecloudhost.com >> ~/.ssh/known_hosts
        eval "$(ssh-agent -s)"
        ssh-add ~/.ssh/consoft_ssh_new  # No passphrase needed now

    # Test SSH Connection
    - name: Test SSH Connection
      run: |
        ssh -v -i ~/.ssh/consoft_ssh_new allevent@s1346.use1.mysecurecloudhost.com "echo 'Connection successful'"

    # Build Frontend
    - name: Build Frontend
      run: |
        cd frontend
        CI=false npm install  # Install frontend dependencies with CI mode off
        CI=false npm run build  # Build the frontend app with CI mode off

    # Deploy Frontend to the Server
    - name: Deploy Frontend via SSH
      run: |
        scp -v -i ~/.ssh/consoft_ssh_new -r ./frontend/build/* allevent@s1346.use1.mysecurecloudhost.com:/home/allevent/reacttest.gephelssystems.com/frontend

    # Install Backend Dependencies
    - name: Install Backend Dependencies
      run: |
        cd backend
        CI=false ssh -i ~/.ssh/consoft_ssh_new allevent@s1346.use1.mysecurecloudhost.com "cd /home/allevent/reacttest.gephelssystems.com/backend && npm install"

    # Deploy Backend to the Server
    - name: Deploy Backend via SSH
      run: |
        scp -v -i ~/.ssh/consoft_ssh_new -r ./backend/* allevent@s1346.use1.mysecurecloudhost.com:/home/allevent/reacttest.gephelssystems.com/

    # Restart Node.js Application on cPanel
    - name: Restart Node.js Application
      run: |
        ssh -i ~/.ssh/consoft_ssh_new allevent@s1346.use1.mysecurecloudhost.com "cd /home/allevent/reacttest.gephelssystems.com && pm2 restart all"  # Assuming PM2 is being used to manage the Node.js app
