name: Deploy React and Node.js to cPanel

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy React and Node.js to cPanel
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the Code
    - name: Checkout Code
      uses: actions/checkout@v2

    # Step 2: Setup Node.js
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 20 # Replace with the required Node.js version

    # Step 4: Install Backend Dependencies
    - name: Install Backend Dependencies
      working-directory: ./backend
      run: |
        npm install --production

    # Step 5: Deploy Backend
    - name: Deploy Backend
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./backend/
        remote-dir: /home/allevent/public_html/consoft-module/backend

    # Step 6: Restart Node.js App on cPanel
    - name: Restart Node.js App
      run: |
        ssh -o StrictHostKeyChecking=no -i ${{ secrets.CPANEL_SSH_PRIVATE_KEY }} ${{ secrets.CPANEL_SSH_USER }}@${{ secrets.CPANEL_SSH_HOST }} "
        cd /home/allevent/public_html/consoft-module/backend &&
        pm2 restart app.js"
      env:
        SSH_PRIVATE_KEY: ${{ secrets.CPANEL_SSH_PRIVATE_KEY }}
