name: Deploy via SSH

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        module: [frontend, user]  # Define frontend and user as two separate matrix jobs
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 2  # Fetch 2 commits (previous commit and current commit)

    # Set up SSH with New Key
    - name: Set up SSH with New Key
      run: |
        set -e
        mkdir -p ~/.ssh
        echo "${{ secrets.CPANEL_SSH_PRIVATE_KEY }}" > ~/.ssh/consoft_ssh_new
        chmod 600 ~/.ssh/consoft_ssh_new
        ssh-keyscan -H s1346.use1.mysecurecloudhost.com >> ~/.ssh/known_hosts
        eval "$(ssh-agent -s)"
        ssh-add ~/.ssh/consoft_ssh_new  # No passphrase needed now

    # Test SSH Connection
    - name: Test SSH Connection
      run: |
        ssh -v -i ~/.ssh/consoft_ssh_new allevent@s1346.use1.mysecurecloudhost.com "echo 'Connection successful'"

    # Check for Changes in the Current Module (Frontend or User)
    - name: Check for Changes in Module
      id: check_changes
      run: |
        module_changes=$(git diff --name-only HEAD~1 HEAD -- ${{ matrix.module }})
        echo "${{ matrix.module }}_changes=$module_changes" >> $GITHUB_ENV
        echo "Changes in ${{ matrix.module }}: $module_changes"

    # Build the Module if Changes are Detected
    - name: Build Module
      if: env.${{ matrix.module }}_changes != ''
      run: |
        cd ${{ matrix.module }}
        CI=false npm install  # Install dependencies with CI mode off
        CI=false npm run build  # Build the module with CI mode off

    # Deploy the Module if Changes are Detected
    - name: Deploy Module via SSH
      if: env.${{ matrix.module }}_changes != ''
      run: |
        ssh -v -i ~/.ssh/consoft_ssh_new allevent@s1346.use1.mysecurecloudhost.com "mkdir -p /home/allevent/reacttest.gephelssystems.com/${{ matrix.module }}/"
        scp -v -i ~/.ssh/consoft_ssh_new -r ./${{ matrix.module }}/build/* allevent@s1346.use1.mysecurecloudhost.com:/home/allevent/reacttest.gephelssystems.com/${{ matrix.module }}/

  deploy_backend:
    runs-on: ubuntu-latest
    needs: deploy  # Ensure frontend and user builds are done before backend deploy
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up SSH with New Key for Backend
    - name: Set up SSH with New Key for Backend
      run: |
        set -e
        mkdir -p ~/.ssh
        echo "${{ secrets.CPANEL_SSH_PRIVATE_KEY }}" > ~/.ssh/consoft_ssh_new
        chmod 600 ~/.ssh/consoft_ssh_new
        ssh-keyscan -H s1346.use1.mysecurecloudhost.com >> ~/.ssh/known_hosts
        eval "$(ssh-agent -s)"
        ssh-add ~/.ssh/consoft_ssh_new  # No passphrase needed now

    # Test SSH Connection
    - name: Test SSH Connection for Backend
      run: |
        ssh -v -i ~/.ssh/consoft_ssh_new allevent@s1346.use1.mysecurecloudhost.com "echo 'Connection successful'"

    # Check for Backend Changes
    - name: Check for Backend Changes
      id: check_backend_changes
      run: |
        # Check if there are enough commits to use HEAD~1 (if not, compare with the initial commit)
        commit_count=$(git rev-list --count HEAD)
        if [ "$commit_count" -gt 1 ]; then
          git diff --quiet HEAD~1 HEAD -- backend || echo "Backend changes detected"
          backend_changes=$(git diff --name-only HEAD~1 HEAD -- backend)
        else
          echo "No previous commits to compare, assuming changes are detected."
          backend_changes="backend changes"
        fi
        echo "backend_changes=$backend_changes" >> $GITHUB_ENV
      continue-on-error: true


    # Deploy Backend if Changes are Detected
    - name: Deploy Backend via SSH
      if: env.backend_changes != ''
      run: |
        scp -v -i ~/.ssh/consoft_ssh_new -r ./backend/* allevent@s1346.use1.mysecurecloudhost.com:/home/allevent/reacttest.gephelssystems.com/

    - name: Restart Node.js Application Using npm start
      if: env.backend_changes != ''
      run: |
        ssh -i ~/.ssh/consoft_ssh_new allevent@s1346.use1.mysecurecloudhost.com "
          source /home/allevent/nodevenv/reacttest.gephelssystems.com/20/bin/activate && 
          cd /home/allevent/reacttest.gephelssystems.com &&
          npm install &&
          npm start
        "
