name: Build and Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install lftp
        run: sudo apt-get update && sudo apt-get install -y lftp

      - name: Create a test file
        run: |
          mkdir -p frontend/build
          echo "This is a test file to check FTP connection" > frontend/build/testfile.txt

      - name: Upload file to CPanel
        run: |
          lftp -d -e "
            open ftp://ftp.gephelssystems.com:21;  # Use FTP instead of SFTP
            user ${{ secrets.FTP_USERNAME }} ${{ secrets.FTP_PASSWORD }}; 
            cd /home/gephelss/public_html/app; 
            put frontend/build/testfile.txt; 
            bye
          "

      - name: Debug Workspace Structure (Optional)
        run: |
          echo "Listing all files in the workspace"
          ls -R
