name: Stop Node.js Application

on:
  workflow_dispatch:

jobs:
  stop_app:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Stop Node.js application
        uses: appleboy/ssh-action@v1.2.0 # Use the latest stable version
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_PRIVATE_KEY }}
          script: |
            cd /home/allevent/reacttest.gephelssystems.com
            if [ -f "pm2.config.js" ]; then
              pm2 stop all
            else
              echo "PM2 configuration not found. Skipping PM2 stop."
              # You can add a fallback for other process managers here, if needed
            fi